// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import ()

type Company struct {
	ID          int32
	CompanyName string
}

type Employee struct {
	ID        int32
	Name      string
	CompanyID int32
}
